server:
  port: 8080
spring:
  application:
    name: cherry-consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: consul-consumer
        # register: false  #设为false代表不注册到注册中心

