server:
  port: 8081
spring:
  application:
    name: cherry-rabbitmq
  rabbitmq:
    host: 121.199.78.8
    port: 15672
    username: guest
    password: guest
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: consul-rabbitmq
    bus:
      trace:
        enabled: true
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

